name = "floofbot"
type = "javascript"
zone_id = ""
account_id = "74e27359ec51d0ca2b0353ee19ce6e65"
route = ""
workers_dev = true
compatibility_date = "2021-10-09"
webpack_config = "webpack.config.js"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
